### ISSUE TITLE
Add description and purpose of the project

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/sdkjs-plugins#1]
This project looks interesting. I wonder what I can do with it.
Is it a way to write plugins to the onlyoffice editor without changing the source code? It would be great if we could do that (like we can do on the CKEditor).

**Comment by K0R0L** [comment]
Yes, you can. Instructions will be released within a month

**Comment by trofim24** [comment]
The new version of Document Server and desktop document editors introduced support for plugins: both visual and non-visual.
[Plugins documentation.](https://api.onlyoffice.com/plugin/basic)
