### ISSUE TITLE
Some plugins load automatically on the 4.3.2 version

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/sdkjs-plugins#12]
Some plugins like Chess (fen), ClipArt, hello world, OCR, Photo Editor, youtube and others are loaded automatically with the 4.3.2 version. Is there any way to disable those plugins to load automatically?

**Comment by trofim24** [comment]
Hey. At the moment, you can disable only by removing unnecessary plugins from the folder sdkjs-plugins or renaming config.json in the folder of a particular plugin.

**Comment by tsmgodoi** [comment]
Thanks, @trofim24 .
