### ISSUE TITLE
"searchAndReplaceOnStart" plugin not working

### ISSUE THREAD

**Issue by cs686** [ONLYOFFICE/sdkjs-plugins#123]
hi,I use searchAndReplaceOnStart plugin， but event not trigger

**Comment by ShockwaveNN** [comment]
Hey @flaminestonem, please take a look

**Comment by flaminestone** [comment]
Hello @cs686. I can confirm - it is bug, №45442 in our internal bugtracker. We wil fix it in future

**Comment by cs686** [comment]
@flaminestone OK, thanks.I use `Common.Gateway` to trigger event,  given in docEditorAPI

**Comment by trofim24** [comment]
[Fixed](https://github.com/ONLYOFFICE/sdkjs/pull/986)
