### ISSUE TITLE
photo editor plugin: Why DOCX only?

### ISSUE THREAD

**Issue by zirkeltraining** [ONLYOFFICE/sdkjs-plugins#13]
Photo Editor is cool! 
But ss there an important reason why the photo editor works only in "Documents" and not in "Spreadsheets"? Because that feature (especially: cropping) is sorely missing there!

**Comment by JohnPerkin** [comment]
Hello @zirkeltraining!
Photo editor plugin has just been released and implemented only in Document editors. Later it will appear in all the editors.

**Comment by trofim24** [comment]
fix

**Comment by zirkeltraining** [comment]
It's great to see you are continuously improving your product. Thanks a lot!
