### ISSUE TITLE
get the name of focus cell

### ISSUE THREAD

**Issue by ThanhLNP** [ONLYOFFICE/sdkjs-plugins#144]
I have an idea that when I select a cell, I will get the name and value of that cell
and I can fill in a certain value in the cell I am selecting
example: When I click on cell B2 I get it address "B2", and it value is "hello"
![image](https://user-images.githubusercontent.com/52529251/109451965-414f0680-7a81-11eb-841c-675d546c396c.png)

I am using sample python code so how can I write it in file editor.html?

Thank you for reading this question

**Comment by ShockwaveNN** [comment]
@askonev Could you take a look, can this be done with our plugin systems?

**Comment by ThanhLNP** [comment]
It's me again
only onlyoffice_desktop_editors can add plugins?
When I follow the instructions here: https://api.onlyoffice.com/plugin/installation
 I get an error
![image](https://user-images.githubusercontent.com/52529251/109615017-f5c25880-7b65-11eb-95b6-d33ab78efc15.png)

**Comment by ShockwaveNN** [comment]
@ThanhLNP Please, leave only one question by issue, so please create a new issue about that. I think your error mean something wrong with syntax of config file, like missing semicolon or something like this

**Comment by askonev** [comment]
Hello @ThanhLNP
Similar to your case, it is implemented in [thesaurus](https://github.com/ONLYOFFICE/plugin-thesaurus) plugin. If you have questions about the implementation, please contact.

Also, some plugins receive select change events.
https://api.onlyoffice.com/plugin/config
You can read the description of this `initOnSelectionChanged` parameter

![Screen record from 2021-03-02 15 58 53](https://user-images.githubusercontent.com/60688343/109652163-78501580-7b70-11eb-84e5-ba7d31b2e4ef.gif)

**Comment by ThanhLNP** [comment]
thank you so much
Wish you every day to grow
