### ISSUE TITLE
Couldn't find pluginBase.js, plugin does not register.

### ISSUE THREAD

**Issue by dmziryanov** [ONLYOFFICE/sdkjs-plugins#145]
Hello, where  can I find a pluginBase.js file?

<script type="text/javascript" src="../pluginBase.js"></script>

I could not register any plugin from the folder and think that is caused by absence of pluginBase.js.

**Comment by ShockwaveNN** [comment]
Hi, could you describe your problem in more details? Which plugin you're trying to register?

**Comment by dmziryanov** [comment]
helloworld plugin.
I found (at  R7-Office\Editors\editors\sdkjs-plugins) and add reference to pluginBase.js in index.html
I packed plugin folder to zip archive and rename to *.plugin
after adding plugin nothing happens.

**Comment by dmziryanov** [comment]
[https://drive.google.com/file/d/11CvP_7-AjwqeS-PMYlRvNDqxEuKDpNNl/view?usp=sharing](url)

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/109510399-0239a900-7ab3-11eb-99c8-b34020ede583.png)

All files should be at root of archive, not in `helloworld` subfolder

**Comment by dmziryanov** [comment]
Ok, thank you.
Plugin appeared at the plugins list, 
![image](https://user-images.githubusercontent.com/11799815/109519195-d62b2180-7acc-11eb-8ea6-fb10bc8ae5ff.png)

but doesn't appear in the toolbox:
![image](https://user-images.githubusercontent.com/11799815/109519404-0672c000-7acd-11eb-969a-3859a81d5d83.png)

**Comment by ShockwaveNN** [comment]
Please attach resulting plugin

**Comment by dmziryanov** [comment]
https://drive.google.com/file/d/1qosaISy6eREcL-83qWX355274WaCFQFi/view?usp=sharing

I suppose pluginBase.js is the base file for plugin and it is located in the root folder with plugin GUID-named folders.
also I noticed that this plugin guid (  "guid"       : "asc.{0616AE85-5DBE-4B6B-A0A9-455C4F1503AD}",) from config json doesn't appear there

**Comment by ShockwaveNN** [comment]
@dmziryanov I've checked your second file right now and it's work fine in ONLYOFFICE DesktopEditors 6.1.0.90 on Kubunut 20.04
![image](https://user-images.githubusercontent.com/668524/109532263-fefde780-7ac9-11eb-984a-995f524075b7.png)

So, could you describe your product version and OS

**Comment by dmziryanov** [comment]
![image](https://user-images.githubusercontent.com/11799815/109536228-4d69b100-7adf-11eb-82d4-e013669c2fa7.png)
1. Windows 10
2. Debian 10

**Comment by ShockwaveNN** [comment]
Could you try to use same plugin with onlyoffice product?
Sorry, but r7 office is separate product and not supported in this repo.

**Comment by dmziryanov** [comment]
ok, i finally worked it out. I tried it in cells, not in docs.
In docs hello world works fine

**Comment by dmziryanov** [comment]
> Could you try to use same plugin with ONLYOFFICE DesktopEditors?
> Sorry, but r7 office is separate product and not supported in this repo.

I supposed this is the same product

**Comment by ShockwaveNN** [comment]
No, those are separate products, I'm gladly help with any issues in ONLYOFFICE, but any problems with r7 should be handled by it's support

I'm close this issue since seems your issue is resolved
