### ISSUE TITLE
[Feature Request] iframe.setAttribute("allow", "autoplay; microphone");

### ISSUE THREAD

**Issue by ThanhLNP** [ONLYOFFICE/sdkjs-plugins#148]
I have an idea to write a speech to text plugin, and it needs to use microphone, can you help me add this:
iframe.setAttribute("allow", "autoplay; microphone");

**Comment by ShockwaveNN** [comment]
@askonev Please take a look and if possible talk with dev team

**Comment by askonev** [comment]
Hi @ThanhLNP
At the moment, permission to use the microphone has been added in server version 6.2 [in this comment](https://github.com/ONLYOFFICE/web-apps/pull/578/commits/9d67f1168310f597605558699f9ec74afc7dff28). Are you using this version?

**Comment by ThanhLNP** [comment]
I am using version 6.1, thanks very much
