### ISSUE TITLE
 [SOLVED] No plugin menu in onlyoffice Doc community edition

### ISSUE THREAD

**Issue by mageunic** [ONLYOFFICE/sdkjs-plugins#150]
Hi !! I'm using onlyoffice Doc community edition 6.2 and I have Nodejs 12.21

**Do you want to request a *feature* or report a *bug*?**
Maybe a bug
**What is the current behaviour?**
There is no plugins menu in onlyoffice interfaces but there is plugins in sdkjs-plugins folder
![image](https://user-images.githubusercontent.com/65236802/111704409-5d072a80-883f-11eb-9216-f19b8bca6841.png)
![image](https://user-images.githubusercontent.com/65236802/111704574-a5264d00-883f-11eb-8370-b90068be8ac4.png)

The only error i have found: in /var/log/onlyoffice/documentserver/docservice/out.log
![image](https://user-images.githubusercontent.com/65236802/111704259-2204f700-883f-11eb-9bbe-94f9312a788d.png)

**Comment by ShockwaveNN** [comment]
Whick DMS are you using? Nextcloud?

**Comment by mageunic** [comment]
Yes, I'm using Nextcloud with onlyoffice Apps

**Comment by ShockwaveNN** [comment]
Thank you for you report, it's a known issue on our end,issue 49007 in our private issue tracker

It's fixed in https://github.com/ONLYOFFICE/web-apps/pull/745

And currently we're working on release 6.2.1 with issue fixed, but it may take some time

**Comment by ShockwaveNN** [comment]
Thanks for noticing, seems I forgot to close this issue
