### ISSUE TITLE
OnlyOffice Desktop Editor add plugin dont working

### ISSUE THREAD

**Issue by 3s-ThanhLNP** [ONLYOFFICE/sdkjs-plugins#152]
I downloaded the chess plugin and added it but nothing happened, even the plugin I wrote myself

At the same time **display-capture** causes an unbootable error with documentserver on chrome

**Comment by ShockwaveNN** [comment]
Could you attach plugin archive you've created?

**Comment by 3s-ThanhLNP** [comment]
u try with https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/chess

**Comment by ShockwaveNN** [comment]
I think your archive structure is incorrect, so I should take a look at result plugin

**Comment by 3s-ThanhLNP** [comment]
[chess.zip](https://github.com/ONLYOFFICE/sdkjs-plugins/files/6270420/chess.zip)
please check, thank you

**Comment by ShockwaveNN** [comment]
You got subfolder inside it

Compare your plugin on the left and correct structure on the right

![image](https://user-images.githubusercontent.com/668524/113843440-3da75180-979c-11eb-98c4-f0b69be71044.png)

**Comment by 3s-ThanhLNP** [comment]
really sorry, i made a big mistake,

in documentserver I see .setAttribute(‘allow’, ‘display-capture’) causing an alert when I use chrome

**Comment by ShockwaveNN** [comment]
@3s-ThanhLNP Could you specify in more details are your problem solved?
Because I don't quite get part about `setAttribute`

**Comment by 3s-ThanhLNP** [comment]
I have tried again many times and I have started documentserver, ‘display-capture’ just causes warning in chrome but not error
Thank you for your enthusiastic help

**Comment by ShockwaveNN** [comment]
@3s-ThanhLNP I see that you're using personal.onlyoffice.com but I cannot understand how did you make your plugin work with personal, this site do not allow adding your own plugins

**Comment by 3s-ThanhLNP** [comment]
Thank you, I tested it on cloud service too and got the not-allowed microphone error as well
And actually the plugin still works on personal version

**Comment by ShockwaveNN** [comment]
> I tested it on cloud service too 

Which cloud version?

**Comment by 3s-ThanhLNP** [comment]
Version 11.5.0
![Capture](https://user-images.githubusercontent.com/76201885/117634345-fea85980-b1a8-11eb-8d03-0046bbff5c15.PNG)

**Comment by ShockwaveNN** [comment]
This is version of CommunityServer, not version of DocumentServer

But I see you're using onlyoffice.sg region

Still I don't get how did you added plugin to cloud version?

**Comment by 3s-ThanhLNP** [comment]
I have followed this tutorial, I think maybe I need more configuration in the manifest.json section

https://www.onlyoffice.com/blog/2019/07/how-to-add-new-plugins-in-onlyoffice-cloud-service-using-chrome-extensions/?utm_source=blog&utm_medium=social&utm_campaign=plugins_for_dev

**Comment by ShockwaveNN** [comment]
Oh, this explains

I'm never tried to to this, but maybe you're right, you should add permissions to [manifest](https://github.com/ONLYOFFICE/sdkjs-plugins/blob/master/chrome_extension_example/manifest.json#L34), explained [here](https://developer.chrome.com/docs/extensions/mv2/declare_permissions/)

**Comment by 3s-ThanhLNP** [comment]
It's weird, I still can use webkitSpeechRecognition in chrome extension, but can't use it at onlyoffcie cloud, I got allow and not-allow at the same time.

![Untitled](https://user-images.githubusercontent.com/76201885/117759033-47195300-b24d-11eb-9c71-8120df429747.png)


tôi đã chạy webkitSpeechRecognition ở "/main.js" hoặc "background.js" ở chrome extension thì không có vấn đề gì, microphone được allow,
 nhưng khi vào đến phần window.Asc.plugin thì webkitSpeechRecognition đã bị blocked
![Untitled](https://user-images.githubusercontent.com/76201885/117759491-14238f00-b24e-11eb-9cc7-64b098ca2a66.png)
![Capture](https://user-images.githubusercontent.com/76201885/117759527-230a4180-b24e-11eb-82fc-b587a36911fa.PNG)

**Comment by ShockwaveNN** [comment]
Could you try to get `chrome_extension_example` from [develop](https://github.com/ONLYOFFICE/sdkjs-plugins/tree/develop/chrome_extension_example)?

I'm not sure but we may fixed some bugs on it

**Comment by ShockwaveNN** [comment]
@DenisDeeSign could you take a look? I'm out of ideas

**Comment by 3s-ThanhLNP** [comment]
Thank you very much, I will continue to find ways in the meantime

**Comment by Rita-Bubnova** [comment]
Sorry for late response.
Please state is this problem still actual for you?

**Comment by Rita-Bubnova** [comment]
This issue was closed due to no response.
