### ISSUE TITLE
how can I get ‘token’value at code of plugins

### ISSUE THREAD

**Issue by edilyxin** [ONLYOFFICE/sdkjs-plugins#158]
hi 
I have a very basic question: how to get the token value of the business code in the plug-in code?I'm using version 6.x onlyoffice.

**Comment by ShockwaveNN** [comment]
> token value of the business code in the plug-in code

Hi I don't get it

Could you describe it more details

Maybe you need to get to Google Chrome Debug tools like this:

![image](https://user-images.githubusercontent.com/668524/123814731-9a7b5980-d8fe-11eb-9904-af4ba2770c53.png)

**Comment by edilyxin** [comment]
Hi 
Thank you for your answer. 
What I mean is to get the token value in the plug-in for authentication.

**Comment by ShockwaveNN** [comment]
Sorry, I still do not understand you, which plugin? Which authentication? 
If you trying to authenticate to some service it's pure JS code - you should authenticate like any other, or for example take a look at [zotero plugin](https://github.com/ONLYOFFICE/plugin-zotero) which require authentication to work

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
