### ISSUE TITLE
Issue: Problem with new lines (\n) in version 7.0.0+

### ISSUE THREAD

**Issue by mbx2015** [ONLYOFFICE/sdkjs-plugins#167]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?** 
Instead of making new line, it print **"\n"** when I insert a paragraph via a plugin (_SearchAndReplace_), in the previous version **6.4.0** was working, now it's a problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Should return to new line not printing **"\n"**

**Did this work in previous versions of DocumentServer?**
**Yes**

**DocumentServer Docker tag:** 7.0.0

**Host Operating System:** 
Docker on both Windows and Linux (debian)

**Comment by l8556** [comment]
@mbx2015 Hi! Please provide more details on what you are doing?
as everything works correctly for me,

I use the [searchAndReplaceOnStart plugin](https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/searchAndReplaceOnStart)
from the master branch of the latest version.

- I add the replacement text to "replaceString" 
"text for example\n text for example text for example text\n\n for example text for example text for example text for example text for example text for example text for example text for example text for example\n text for example text for example text for example text for example\n\n text for example text for example text for example text for example"

The result of the plugin's work is on the screenshot
![image_2022-03-16_14-34-24](https://user-images.githubusercontent.com/52069739/158581811-76910146-bc81-4a84-977b-8592205ec959.png)

ds 7.0.0.133

Could you attach plugin you've using? Maybe it's used some old code?

**Comment by mbx2015** [comment]
Hi @l8556 ,
Here is the plugin code I work with:
[search-replace.zip](https://github.com/ONLYOFFICE/sdkjs-plugins/files/8304076/search-replace.zip)

**Comment by l8556** [comment]
@mbx2015
Please provide a link to our examples or plugins.

If you wrote your own plugin and use it,
specify the method you think is inconsistent with the documentation and doesn't work correctly.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
