### ISSUE TITLE
[feature] Get element's page number

### ISSUE THREAD

**Issue by nitely** [ONLYOFFICE/sdkjs-plugins#17]
I'm trying to auto-generate a *table of content*. I wonder if it's possible to have an API that returns the current page number for a given element. Something like:

```javascript
var oDocument = Api.GetDocument();
var elm = oDocument.GetElement(0);
elm.getPageNumber();
```

Not sure if this is the right place to ask this.

**Comment by agolybev** [comment]
Hi @nitely. Thank you for iinterest to Onlyoffice DocumentServer.
We are implementing _table of content_ feature in Document Server now. We are going to add such functionality for documentserver plugins afterwards.
