### ISSUE TITLE
When use thew plugins settings, the command "crtl+c" is invalid

### ISSUE THREAD

**Issue by th8664484** [ONLYOFFICE/sdkjs-plugins#184]
The same problem
https://github.com/ONLYOFFICE/DocumentServer/issues/1486 
Reply in
link 404
https://github.com/ONLYOFFICE/sdkjs-plugins/blob/master/settings/code.js#L7

Please reply me the following again, thank you

**Comment by trofim24** [comment]
you can read [our documentation ](https://api.onlyoffice.com/plugin/executemethod/common/setproperties)about `SetProperties`
