### ISSUE TITLE
Плагины , интеграция с базами данных 

### ISSUE THREAD

**Issue by er77** [ONLYOFFICE/sdkjs-plugins#185]
День добрый . 

   Подскажите пж. есть ли возможность создавать расшиернеия для Р7 , которые будут работать нативно с компьютером 
 Например , включать в себя драйвера базы данных , работать с файловой системой ? 

ЕР

**Comment by ibnpetr** [comment]
Hello 
We appreciate you submitting the issue in the ONLYOFFICE repo, but your question is completely unclear.
Feel free to contact us if you have any technical inquiries about the ONLYOFFICE product.
When submitting an issue, make sure that all fields have been filled in.
