### ISSUE TITLE
ContextMenu items click-events doesn't handle

### ISSUE THREAD

**Issue by qTemiO** [ONLYOFFICE/sdkjs-plugins#187]
Greetings everyone, just tested this guide

https://api.onlyoffice.com/plugin/example/contextmenuandevents

After that checked GPT and ZhiPu Copiplot Open Source plugins to test...

Problem in this event handlers
```html 
window.Asc.plugin.attachContextMenuClickEvent("menu_item_id", function () {
    window.Asc.plugin.executeMethod('GetSelectedText', null, function(text) {
	console.log(text)
    });
});
```
After debug i noticed that body of this method never called at all

Writing on clean JS, readed this material to make own plugin
https://api.onlyoffice.com/plugin/basic

Using OnlyOffice Document Server, Docker

Tested at Edge, Mozilla, Chrome

I Have no idea how to solve this misshandling events

Please give me a hint what i am missing, thanks

**Comment by qTemiO** [comment]
Hello again, i find solution

You should access your Document, and Paragraph or something you need to edit

For example in this lines 

```html
Asc.scope.text = "hello github!";
var oDocument = Api.GetDocument();
var oParagraph = Api.CreateParagraph();
oParagraph.AddText(Asc.scope.text);
oDocument.InsertContent([oParagraph]);
```

Then, by the event you can handle any edit of your document  

```html
window.Asc.plugin.attachContextMenuClickEvent('id_of_your_event_in_context_menu', function () {
    window.Asc.plugin.executeMethod('GetSelectedText', null, function(text) {
          // put here upper recomendations         
          // or any handlers you need
    };
});
```

You can't change your document without having access to his paragraphs or something.
My recommendation to OnlyOffice developers - take a look of your documentation, especially Plugins Examples. I linked in my message upper not working example.

Really sorry for my issue, i'm new to JS, needed some time to solve this case)

**Comment by langziyang** [comment]
hello, can you show your full code please
