### ISSUE TITLE
Is there a way to put the plugin icon on the main toolbar?

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/sdkjs-plugins#2]
I've managed to run the plugins. But I need to put its icon on the main toolbar. Is there a way to do it?

**Comment by K0R0L** [comment]
Thank you for your interest). Look plug-ins are in the editor as follows:

![plugins](https://cloud.githubusercontent.com/assets/16754960/17286172/6e922f92-57d0-11e6-9da1-054660a92b22.jpg)


Try it - the easiest way is: take the plugin (eg chess), to archive the contents of a folder (not the folder) in the zip archive, rename to chess.plugin and do drag drop the resulting file to the desktop editor main page. Instructions on how to write plug-ins, how to include everyone on the server, or separately for each user in the Web version, or installed in a desktop - will be released within a month.

**Comment by tsmgodoi** [comment]
Thanks for the feedback. I've managed to run the plugins on the web version. This is an exciting feature. It would be nice if we could customize the upper toolbar to include a plugin button too. Another interesting feature would be the ability of a plugin to be initialized automatically, so we could intercept some events automatically.
Keep up the good work with this awesome project!

**Comment by trofim24** [comment]
`variations.icons` - Plugin icon image files used in the editors.
https://api.onlyoffice.com/plugin/config
