### ISSUE TITLE
Plugins which use the document object don't work with the minified production code

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/sdkjs-plugins#3]
I've managed to run the plugins by replacing the folder /var/www/onlyoffice/documentserver/ inside the docker with the the original sources. Without it my plugin code cannot use some Document methods.
I keep getting:
oDocument.Document.Get_CurrentParagraph is not a function(…)
It happens with this code:

var oDocument = Api.GetDocument();
var oCurrentParagraph = oDocument.Document.Get_CurrentParagraph();

Is this plugin mechanism production ready? I didn't see any documentation anywhere. Thanks.

**Comment by K0R0L** [comment]
Instructions will be released within a month.

**Comment by trofim24** [comment]
[WRITING THE PLUGIN CODE.](https://api.onlyoffice.com/plugin/code)
[PLUGIN EXAMPLE](https://api.onlyoffice.com/plugin/example)
[ONLYOFFICE Document Builder](https://helpcenter.onlyoffice.com/developers/document-builder/index.aspx) - this is how the plugins interact with the editors.
