### ISSUE TITLE
Macros Plugin doesn't keep the macro definition

### ISSUE THREAD

**Issue by mhauschild** [ONLYOFFICE/sdkjs-plugins#31]
Hey guys,

I just installed the macro plugin on my document server instance by drag 'n' dropping the macros folder.

The macros plugin is displayed accordingly and works like expected. After leaving the macro editor and entering again all macro definitions are gone.

Any hints or same issues with that plugin?

Thanks in advance.
-Using Onlyoffice Document Server v5.0.7-38
-plugin base v0.7.1
-macro version pulled today

**Comment by K0R0L** [comment]
Hello.
Correct work only in desktop editors. In the server version, macroses will work correctly from version 5.1. This version is now in testing...

**Comment by mhauschild** [comment]
Thanks for the quick feedback.
Is there any timeline when the new version will be released?

**Comment by K0R0L** [comment]
between the end of February and the middle of March

**Comment by trofim24** [comment]
https://github.com/ONLYOFFICE/DocumentServer/releases/tag/ONLYOFFICE-DocumentServer-5.1.0
