### ISSUE TITLE
PasteHtml method can paste data only with default style

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/sdkjs-plugins#39]
Method `PasteHtml` paste text with default style, if it style is not setted in html.
Example:
```
(function(window, undefined) {
  window.Asc.plugin.init = function() {
    window.Asc.plugin.executeMethod("PasteHtml", ['<span>text</span>'], false);
    this.executeCommand("close", '');
  };
})(window, undefined);
```
![gifout](https://user-images.githubusercontent.com/6047261/47565279-a1bd5e80-d930-11e8-8eaf-5bb3fd5a1f94.gif)

It is correct behavior? Or text must paste with paragraph style?

**Comment by flaminestone** [comment]
I create bug in our private bugtracker №39603

**Comment by flaminestone** [comment]
Is fixed in 5.2.5.4

**Comment by lsacchet** [comment]
Font not working yet ???

**Comment by lsacchet** [comment]
I believe it is related. Method "PasteHtml" applies to default font.

**Comment by ShockwaveNN** [comment]
@lsacchet Ah, ok, we'll take a look, thanks
