### ISSUE TITLE
Image Editor Non-Functional in Desktop Editors

### ISSUE THREAD

**Issue by wes3161** [ONLYOFFICE/sdkjs-plugins#45]
Currently the photo editor is broken within desktop editors, when editing a photo, any changes will caused the photo become transparent and replaced with an empty box.

Tested under 5.2.80.470 of desktop editors on Ubuntu 18.04

**Comment by Rita-Bubnova** [comment]
Hello, @wes3161.
Thank you. I can confirm - this is a bug, issue 37864 in our internal issue tracker.

**Comment by Rita-Bubnova** [comment]
Your problem is fixed and released as 5.3.
