### ISSUE TITLE
Photo Editor-Plugin - Error reaching Aviary services

### ISSUE THREAD

**Issue by R2DPIO** [ONLYOFFICE/sdkjs-plugins#50]
also getting same error if i try the plugin at "https://api.onlyoffice.com/editors/demopreview?type=text#DemoPreview"
Chrome and Firefox...

![image](https://user-images.githubusercontent.com/43437349/55960220-9c4c9a00-5c6c-11e9-9ffc-23a0f2a86f82.png)

any ideas?

**Comment by R2DPIO** [comment]
> Hello, @R2DPIO.
> Thank you. We know about this problem, issue 41170 in our private issue tracker.

Ok, thank you. 
Do you have any information about the status of this issue? Last week it worked sometimes but now its not working again...

**Comment by ShockwaveNN** [comment]
@R2DPIO We used 3d party service to provide photo editor abilities and it changed.
We'll remove this plugin all-together in 5.3, but we planning to implement our own photo editor in future

**Comment by R2DPIO** [comment]
thank you for this information! So I can tell my staff that it will take time...

**Comment by e-alfred** [comment]
The service is also broken if Onlyoffice is run within Nextcloud, see issue https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/260.

**Comment by hifihedgehog** [comment]
Any ETA on a fix? I have been using ONLYOFFICE within Nextcloud and this issue has persisted for several months.

**Comment by ShockwaveNN** [comment]
@hifihedgehog We planning to release completely new Photo Editor with DocumentServer 5.3 soon

**Comment by trofim24** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
