### ISSUE TITLE
The search for synonyms of words does not work using the plugin "Thesaurus"

### ISSUE THREAD

**Issue by Rita-Bubnova** [ONLYOFFICE/sdkjs-plugins#78]
Steps to reproduce:

1. Open a new DOCX document.
2. Enter the word "Hello".
3. Highlight the word "Hello".
4. Start plugin "Thesaurus".
5. In the plugin tab "Thesaurus" press "Lookup".

Result:
Synonyms for the word "Hello" are not displayed.
The word “Hello” is used as an example; the plugin does not work with other words.

**Comment by sh2515** [comment]
I can confirm that this is happening to the installation here. Used to work but now isn't.

**Comment by Rita-Bubnova** [comment]
I rechecked on DocumentServer v6.4.2.6 and the problem is not actual anymore (I use Chrome 95.0.4638.69, Windows 11).
