### ISSUE TITLE
[feature]I hope to get the content and the coords of a selected cell range in plugins

### ISSUE THREAD

**Issue by cnTailor** [ONLYOFFICE/sdkjs-plugins#87]
**in the version 5.4**

When I selected a range, then I open a plugin the `plugin.init(text)` is called, the param text just has the cell content, but no the coordinates of the range. 

can we add a param in the `plugin.init(text, range)` , param range is a string like `E9:G12`, means the  the left top corner coordinates and right bottom coordinates of cell range.

**Comment by bopro** [comment]
`window.parent.SSE.controllers.Main.api.asc_getDefaultDefinedName().Ref`
or
`window.parent.SSE.controllers.DocumentHolder.api.asc_getDefaultDefinedName().Ref`

**Comment by cnTailor** [comment]
Thanks @bopro , I got it!
