### ISSUE TITLE
How to replace paragraphs？

### ISSUE THREAD

**Issue by szyuanyang** [ONLYOFFICE/sdkjs-plugins#90]
hi~~

I have a section of JSON data. I need to replace a section of the word document. How should I operate it? Thank you.

example:
`date=[
    {"company":"abc","title":"bbbbbbbbbb","content":"eeeeeeeeeeeeeeeeeeeee"},
    {"company":"abc","title":"bbbbbbbbbb","content":"eeeeeeeeeeeeeeeeeeeee111"},
    {"company":"abc","title":"bbbbbbbbbb","content":"eeeeeeeeeeeeeeeeeeeee222"},
    {"company":"abc","title":"bbbbbbbbbb","content":"eeeeeeeeeeeeeeeeeeeee333"}
]`

replace word paragraph:
![rr](https://user-images.githubusercontent.com/26141856/70006111-ed682000-15a6-11ea-9498-3b2862cdc806.png)

**Comment by flaminestone** [comment]
Hi. I don't understand  what part of data you want to replace? Do you need to increase (or change it in any other way) value of `content` key each time it is repeated?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
